### ISSUE TITLE
Other datasets

### ISSUE THREAD

**Issue by zhangsirui-sir** [lixiaoyu2000/Poly-MOT#19]
Hello, thank you for your contribution to the open source cause. I would like to ask you how to test on other data sets due to device limitations, such as nuscene-mini, KITTI, Waymo, etc. If you are lucky enough to get your reply I will be extremely grateful！

**Comment by lixiaoyu2000** [comment]
We have no plans to support other datasets at the moment. However, since Poly-MOT is tracked in the global coordinate system (right-hand rule coordinate system), you only need to provide the detector conversion script (waymo-to-nuscenes, kitti-to-nuscenes, etc.) to make Poly-MOT seamlessly runs in any right-hand rule dataset.
