### ISSUE TITLE
Real-time

### ISSUE THREAD

**Issue by flora077** [lixiaoyu2000/Poly-MOT#22]
Hello, author. I would like to know if you have made any comparisons with AB3DMOT, especially in terms of FPS differences when running on the same dataset, such as KITTI or NUscenes. I am eager to find out about this because I see that AB3DMOT performs exceptionally well in real-time on KITTI, and I wonder if Poly-MOT can achieve the same effect.

**Comment by lixiaoyu2000** [comment]
There is currently no comparison with AB3DMOT. However, I believe Poly-MOT can achieve real-time performance (>30FPS) on KITTI or road test, since we have tested that Poly-MOT can achieve >50FPS on an embedded robotic platform (NVIDIA Jetson AGX Orin, road test, message with ROS, Python implementation). In addition, ref to [this issue](https://github.com/lixiaoyu2000/Poly-MOT/issues/19), you can develop Poly-MOT to KITTI for accurate inference speed.

**Comment by lixiaoyu2000** [comment]
Issue closed due to inactivity.
