### ISSUE TITLE
Kalman Filter measurement info (getMeasureInfo)

### ISSUE THREAD

**Issue by KevinCodeGitHub** [lixiaoyu2000/Poly-MOT#30]
Thank you for your excellent work! I've been working on understanding the Kalman filter, and I have a question regarding an uncertainty I'm encountering.
 In        
 https://github.com/lixiaoyu2000/Poly-MOT/blob/5fead68f88ec41af71c789da0f52a6f11a290891/motion_module/kalman_filter.py#L66
 you use 'nusc_box' as measurement info, sourced from the following dictionary:
``` 
dict_det = {
                'nusc_box': data_info['box_dets'][det_idx],
                'np_array': data_info['np_dets'][det_idx],
                'has_velo': data_info['has_velo'],
                'seq_id': data_info['seq_id']
            }
```
Based on my understanding, both 'nusc_box' and 'np_array' seem to contain the same information but in different formats. Could you explain why you opted to use 'nusc_box' instead of continuing to use 'np_array'? 
 https://github.com/lixiaoyu2000/Poly-MOT/blob/5fead68f88ec41af71c789da0f52a6f11a290891/motion_module/kalman_filter.py#L66

**Comment by lixiaoyu2000** [comment]
Hi, your understanding is correct. We have retained the detection interface of two data types (`np.ndarray`, `nusc_box`). The reason we use `nusc_box` within `concat_box_attr` is because of the previous [line](https://github.com/lixiaoyu2000/Poly-MOT/blob/main/motion_module/kalman_filter.py#L65), we can use string attributes to extract the in-class properties, which is safer and more readable. Besides, `np.ndarray` is more friendly to parallelization. You can see in this [file](https://github.com/lixiaoyu2000/Poly-MOT/blob/main/geometry/nusc_distance.py) how we use numpy for parallel operations.

**Comment by lixiaoyu2000** [comment]
Issue closed due to inactivity.
