### ISSUE TITLE
Have you ever tested detection results without a speed attribute as input to the tracker?

### ISSUE THREAD

**Issue by windzu** [lixiaoyu2000/Poly-MOT#8]
First of all, thank you very much for your contribution. The thought process in your article is very clear.

I have been recently studying some tracking methods based on filters and found that your paper has done a great job.

However, after reading your paper, I have a question (sorry, I haven't looked at your code yet). Many custom datasets do not have ground truth values for velocity (v), so when training 3D detection models using these datasets, the common approach is to discard the velocity. For example, the famous 3D detection network you used, CenterPoint, doesn't utilize the velocity information in our custom dataset. It is evident that having velocity information is very helpful for predicting the trajectory of an object. Therefore, I am curious whether the performance of the tracker would significantly decrease when not using velocity as an input. The outcome of this test will directly influence whether I should train models with velocity in my subsequent research. I hope you can find time to answer this when you're available.

**Comment by lixiaoyu2000** [comment]
Hi,  actually you can test Poly-MOT without speed. We include whether the detector contains speed in the [config](https://github.com/lixiaoyu2000/Poly-MOT/blob/main/config/nusc_config.yaml#L3). As you might expect, no speed infos comes with a loss of accuracy. However, the drop is not significant (My vague memory is that: about 0.5 AMOTA), which is caused by our motion model can rely on displacement to infer velocity in the kalman filter.

**Comment by lixiaoyu2000** [comment]
Issue closed due to inactivity.
